verplicht het toepassen van de standaard Federated Service Connectivity
Logius-standaarden/Digikoppeling-Koppelvlakstandaard-REST-API pull request #27
Opened 2023-12-18 10:25 UTC by ronaldkoster

Zie https://github.com/Logius-standaarden/Digikoppeling-Koppelvlakstandaard-REST-API/issues/26

2024-01-30 09:26 UTC, mrtn78 requested changes

2024-01-30 09:26 UTC, mrtn78 commented on ch03_Digikoppeling Restful API profiel.md
> +* Zie [FSC](https://commonground.gitlab.io/standards/fsc/)
Hier graag een verdere duiding maken van de 3 onderliggende standaarden en direct verwijzen naar de 3 documenten.

1. Core

    [html](https://commonground.gitlab.io/standards/fsc/core/draft-fsc-core-00.html)

2. Delegation

    [html](https://commonground.gitlab.io/standards/fsc/delegation/draft-fsc-delegation-00.html)

3. Logging

    [html](https://commonground.gitlab.io/standards/fsc/logging/draft-fsc-logging-00.html)

2024-01-30 09:26 UTC, mrtn78 commented on ch03_Digikoppeling Restful API profiel.md
> +FSC spreekt over een Thrust Anchor die door een Group moet worden gekozen. De Trust Anchor is binnen de context van X.509 certificaten de certificate authority (CA) waaruit het vertrouwen wordt afgel
```suggestion
FSC spreekt over een Trust Anchor die door een Group moet worden gekozen. De Trust Anchor is binnen de context van X.509 certificaten de certificate authority (CA) waaruit het vertrouwen wordt afgeleid.
```

2024-01-30 09:26 UTC, mrtn78 commented on ch03_Digikoppeling Restful API profiel.md
> +Het verplicht vanuit FSC om te bepalen welk veld uit het certificaat de Peer name bepaald. Dit is het organization veld van het Subject van het PKIO certificaat.
```suggestion
Het is verplicht vanuit FSC om te bepalen welk veld uit het certificaat de Peer name bepaald. Dit is het organization veld van het Subject van het PKIO certificaat.
```

2024-01-30 09:26 UTC, mrtn78 commented on ch03_Digikoppeling Restful API profiel.md
> +Voorbeeld: Peer A verstuurt een Contract naar Peer B. Het versturen mislukt. Peer A probeert het opnieuw na 1 seconde, het verzoek mislukt weer. De volgende poging wordt gedaan na 2 seconden, daarna
Is dit interval en deze maximum waarde een vereiste of alleen een voorbeeld. En als dit alleen een voorbeeld is waar worden deze afspraken dan gemaakt en vastgelegd?

2024-01-30 09:26 UTC, mrtn78 commented on ch03_Digikoppeling Restful API profiel.md
> +Deze exponentiële groei voorkomt dat een applicatie een veelfout van verzoeken verstuurd naar een service die niet bereikbaar is.
```suggestion
Deze exponentiële groei voorkomt dat een applicatie een veelvoud van verzoeken verstuurd naar een service die niet bereikbaar is. 
```

2024-02-01 08:56 UTC, edwinwisse commented on ch03_Digikoppeling Restful API profiel.md
> +Daarnaast is de standaard Federated Service Connectivity (FSC) ontwikkelt die voorschrijft hoe organisaties REST API's kunnen ontdekken, aanbieden en consumeren. De FSC standaard is opgenomen in dit
ontwikkeld (ipv ontwikkelt)

2024-02-05 08:56 UTC, mrtn78 approved these changes

2024-02-14 13:46 UTC, PHaasnoot approved these changes

2024-03-04 10:39 UTC, strijm commented on ch03_Digikoppeling Restful API profiel.md
> +Binnen dit Digikoppeling REST API profielprofiel zijn er alleen voorschriften m.b.t. het verplicht gebruik van het OIN binnen PKIO certificaten en FSC. Voor OIN gebruik binnen payloads (bv JSON) of r
profielprofiel -> profiel

2024-03-06 10:25 UTC, kad-vijlbc commented on ch03_Digikoppeling Restful API profiel.md
> +FSC plaatst geen beperking op het aantal Grants per Contract. Het Digikoppeling REST API profiel doet dit wel om te voorkomen dat er fragiele Contracten ontstaan met een hoge beheerslast. Het aantal
Deze beperking van 10 lijkt mij in praktijk wel een issue. Hoe gaan we hier mee om? Meerdere contracten opstellen? De beperking van 10 kon ik ook niet zo snel vinden in het REST API profiel (link toevoegen?)

2024-06-11 10:54 UTC, merged